apiVersion: v1
kind: Service
metadata:
  name: baro-buyer
  namespace: baro-prod
  labels:
    app: baro-buyer
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: baro-buyer

