apiVersion: v1
kind: Service
metadata:
  name: baro-order
  namespace: baro-prod
  labels:
    app: baro-order
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
  selector:
    app: baro-order

