apiVersion: v1
kind: Service
metadata:
  name: baro-auth
  namespace: baro-prod
  labels:
    app: baro-auth
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: baro-auth

