apiVersion: v1
kind: Service
metadata:
  name: baro-support
  namespace: baro-prod
  labels:
    app: baro-support
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
      name: http
  selector:
    app: baro-support

