apiVersion: v1
kind: Service
metadata:
  name: baro-seller
  namespace: baro-prod
  labels:
    app: baro-seller
    component: app
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: baro-seller

